server:
  port: 9090


spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: public-service-api
          uri: http://localhost:8080
          predicates:
            - Path=/service-api/open-api/**
          filters:
            - RewritePath=/service-api(?<segment>/?.*), $\{segment}
            - ServiceApiPublicFilter

internal-api:
  account:
    url: http://localhost:8082