spring:
  config:
    import: classpath:env.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
springdoc:
  swagger-ui:
    path: /swagger-ui.html

token:
  access-token:
    ttl-hour: 1
  refresh-token:
    ttl-hour: 12